import { EVModel } from "./types";

export const EV_DATABASE: EVModel[] = [
  {
    id: "tesla-model-3-lr",
    make: "Tesla",
    model: "Model 3 Long Range",
    year: 2024,
    batteryKwh: 82,
    rangeMiles: 358,
    maxChargekW: 250,
    efficiencyMilesPerKwh: 4.37,
  },
  {
    id: "tesla-model-y-lr",
    make: "Tesla",
    model: "Model Y Long Range",
    year: 2024,
    batteryKwh: 82,
    rangeMiles: 330,
    maxChargekW: 250,
    efficiencyMilesPerKwh: 4.02,
  },
  {
    id: "tesla-model-s",
    make: "Tesla",
    model: "Model S",
    year: 2024,
    batteryKwh: 100,
    rangeMiles: 405,
    maxChargekW: 250,
    efficiencyMilesPerKwh: 4.05,
  },
  {
    id: "hyundai-ioniq9-lr",
    make: "Hyundai",
    model: "IONIQ 9 Long Range AWD",
    year: 2025,
    batteryKwh: 110.3,
    rangeMiles: 335,
    maxChargekW: 350,
    efficiencyMilesPerKwh: 3.04,
  },
  {
    id: "hyundai-ioniq9-std",
    make: "Hyundai",
    model: "IONIQ 9 Standard RWD",
    year: 2025,
    batteryKwh: 88.3,
    rangeMiles: 280,
    maxChargekW: 350,
    efficiencyMilesPerKwh: 3.17,
  },
  {
    id: "hyundai-ioniq6",
    make: "Hyundai",
    model: "IONIQ 6 Long Range RWD",
    year: 2024,
    batteryKwh: 77.4,
    rangeMiles: 361,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 4.67,
  },
  {
    id: "kia-ev6-sr",
    make: "Kia",
    model: "EV6 Standard Range RWD",
    year: 2022,
    batteryKwh: 58,
    rangeMiles: 232,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 4.0,
  },
  {
    id: "kia-ev6-lr",
    make: "Kia",
    model: "EV6 Long Range RWD",
    year: 2024,
    batteryKwh: 77.4,
    rangeMiles: 310,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 4.0,
  },
  {
    id: "kia-ev6-awd",
    make: "Kia",
    model: "EV6 GT-Line AWD",
    year: 2024,
    batteryKwh: 77.4,
    rangeMiles: 274,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 3.54,
  },
  {
    id: "kia-ev6-gt",
    make: "Kia",
    model: "EV6 GT",
    year: 2023,
    batteryKwh: 77.4,
    rangeMiles: 206,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 2.66,
  },
  {
    id: "kia-ev9-lr",
    make: "Kia",
    model: "EV9 Long Range AWD",
    year: 2024,
    batteryKwh: 99.8,
    rangeMiles: 280,
    maxChargekW: 240,
    efficiencyMilesPerKwh: 2.81,
  },
  {
    id: "chevy-bolt-euv",
    make: "Chevrolet",
    model: "Bolt EUV",
    year: 2023,
    batteryKwh: 65,
    rangeMiles: 247,
    maxChargekW: 55,
    efficiencyMilesPerKwh: 3.8,
  },
  {
    id: "ford-f150-lightning",
    make: "Ford",
    model: "F-150 Lightning Extended Range",
    year: 2024,
    batteryKwh: 131,
    rangeMiles: 320,
    maxChargekW: 150,
    efficiencyMilesPerKwh: 2.44,
  },
  {
    id: "rivian-r1t",
    make: "Rivian",
    model: "R1T Large Pack",
    year: 2024,
    batteryKwh: 135,
    rangeMiles: 314,
    maxChargekW: 220,
    efficiencyMilesPerKwh: 2.33,
  },
  {
    id: "bmw-i4-edrive40",
    make: "BMW",
    model: "i4 eDrive40",
    year: 2024,
    batteryKwh: 83.9,
    rangeMiles: 301,
    maxChargekW: 205,
    efficiencyMilesPerKwh: 3.59,
  },
  {
    id: "vw-id4-pro",
    make: "Volkswagen",
    model: "ID.4 Pro",
    year: 2024,
    batteryKwh: 82,
    rangeMiles: 275,
    maxChargekW: 135,
    efficiencyMilesPerKwh: 3.35,
  },
  {
    id: "lucid-air-gt",
    make: "Lucid",
    model: "Air Grand Touring",
    year: 2024,
    batteryKwh: 112,
    rangeMiles: 516,
    maxChargekW: 300,
    efficiencyMilesPerKwh: 4.6,
  },
  {
    id: "mercedes-eqe",
    make: "Mercedes-Benz",
    model: "EQE 350+",
    year: 2024,
    batteryKwh: 96.1,
    rangeMiles: 305,
    maxChargekW: 170,
    efficiencyMilesPerKwh: 3.17,
  },
];

// Typical non-member DCFC rates, 2026 US market survey
export const DEFAULT_NETWORK_PRICES: Record<string, number> = {
  "Tesla": 0.40,
  "Electrify America": 0.56,
  "ChargePoint": 0.48,
  "Blink": 0.59,
  "EVgo": 0.55,
  "Francis Energy": 0.39,
  "Shell Recharge": 0.52,
  "Volta": 0.49,
  "Rivian": 0.44,
  "bp pulse": 0.55,
  "Buc-ee's": 0.40,
  "Default": 0.45,
};

export function getEVById(id: string): EVModel | undefined {
  return EV_DATABASE.find((ev) => ev.id === id);
}
