import { EVModel } from "./types";

// Profiles are split by spec-generation: each entry's year range only spans the
// model years where its battery / range / charge-rate are actually constant.
// EVs get yearly EPA tweaks and mid-cycle refreshes (e.g. Model 3 Highland,
// EV6 2025 84 kWh pack), so a broad range would misplan for the off-spec years.
// efficiencyMilesPerKwh = EPA rangeMiles / usable batteryKwh.
export const EV_DATABASE: EVModel[] = [
  {
    id: "tesla-model-3-lr",
    make: "Tesla",
    model: "Model 3 LR AWD",
    years: "2021-2023",
    batteryKwh: 82,
    rangeMiles: 358,
    maxChargekW: 250,
    efficiencyMilesPerKwh: 4.37,
  },
  {
    id: "tesla-model-3-lr-highland",
    make: "Tesla",
    model: "Model 3 LR AWD (Highland)",
    years: "2024-2025",
    batteryKwh: 79,
    rangeMiles: 341,
    maxChargekW: 250,
    efficiencyMilesPerKwh: 4.32,
  },
  {
    id: "tesla-model-y-lr",
    make: "Tesla",
    model: "Model Y LR AWD",
    years: "2021-2023",
    batteryKwh: 82,
    rangeMiles: 330,
    maxChargekW: 250,
    efficiencyMilesPerKwh: 4.02,
  },
  {
    id: "tesla-model-y-lr-2024",
    make: "Tesla",
    model: "Model Y LR AWD",
    years: "2024",
    batteryKwh: 82,
    rangeMiles: 310,
    maxChargekW: 250,
    efficiencyMilesPerKwh: 3.78,
  },
  {
    id: "tesla-model-s",
    make: "Tesla",
    model: "Model S",
    years: "2021-2024",
    batteryKwh: 100,
    rangeMiles: 405,
    maxChargekW: 250,
    efficiencyMilesPerKwh: 4.05,
  },
  {
    id: "hyundai-ioniq9-lr",
    make: "Hyundai",
    model: "IONIQ 9 LR AWD",
    years: "2025",
    batteryKwh: 110.3,
    rangeMiles: 335,
    maxChargekW: 350,
    efficiencyMilesPerKwh: 3.04,
  },
  {
    id: "hyundai-ioniq9-std",
    make: "Hyundai",
    model: "IONIQ 9 SR",
    years: "2025",
    batteryKwh: 88.3,
    rangeMiles: 280,
    maxChargekW: 350,
    efficiencyMilesPerKwh: 3.17,
  },
  {
    id: "hyundai-ioniq6",
    make: "Hyundai",
    model: "IONIQ 6 LR",
    years: "2023-2024",
    batteryKwh: 77.4,
    rangeMiles: 361,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 4.67,
  },
  {
    id: "hyundai-ioniq5-lr-rwd",
    make: "Hyundai",
    model: "IONIQ 5 LR RWD",
    years: "2022-2024",
    batteryKwh: 77.4,
    rangeMiles: 303,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 3.91,
  },
  {
    id: "kia-ev6-sr",
    make: "Kia",
    model: "EV6 Light RWD",
    years: "2022-2024",
    batteryKwh: 58,
    rangeMiles: 232,
    maxChargekW: 180,
    efficiencyMilesPerKwh: 4.0,
  },
  {
    id: "kia-ev6-lr",
    make: "Kia",
    model: "EV6 LR RWD",
    years: "2022-2024",
    batteryKwh: 77.4,
    rangeMiles: 310,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 4.0,
  },
  {
    id: "kia-ev6-lr-2025",
    make: "Kia",
    model: "EV6 LR RWD",
    years: "2025",
    batteryKwh: 84,
    rangeMiles: 319,
    maxChargekW: 240,
    efficiencyMilesPerKwh: 3.8,
  },
  {
    id: "kia-ev6-wind-awd-2022",
    make: "Kia",
    model: "EV6 Wind AWD",
    years: "2022",
    batteryKwh: 77.4,
    rangeMiles: 274,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 3.54,
  },
  {
    id: "kia-ev6-wind-awd",
    make: "Kia",
    model: "EV6 Wind AWD",
    years: "2023-2024",
    batteryKwh: 77.4,
    rangeMiles: 282,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 3.64,
  },
  {
    id: "kia-ev6-wind-awd-2025",
    make: "Kia",
    model: "EV6 Wind AWD",
    years: "2025",
    batteryKwh: 84,
    rangeMiles: 295,
    maxChargekW: 240,
    efficiencyMilesPerKwh: 3.51,
  },
  {
    id: "kia-ev6-awd",
    make: "Kia",
    model: "EV6 GT-Line AWD",
    years: "2023-2024",
    batteryKwh: 77.4,
    rangeMiles: 252,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 3.26,
  },
  {
    id: "kia-ev6-gtline-awd-2025",
    make: "Kia",
    model: "EV6 GT-Line AWD",
    years: "2025",
    batteryKwh: 84,
    rangeMiles: 270,
    maxChargekW: 240,
    efficiencyMilesPerKwh: 3.21,
  },
  {
    id: "kia-ev6-gt",
    make: "Kia",
    model: "EV6 GT",
    years: "2023",
    batteryKwh: 77.4,
    rangeMiles: 206,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 2.66,
  },
  {
    id: "kia-ev6-gt-2024",
    make: "Kia",
    model: "EV6 GT",
    years: "2024",
    batteryKwh: 77.4,
    rangeMiles: 218,
    maxChargekW: 233,
    efficiencyMilesPerKwh: 2.82,
  },
  {
    id: "kia-ev9-lr",
    make: "Kia",
    model: "EV9 LR AWD",
    years: "2024-2025",
    batteryKwh: 99.8,
    rangeMiles: 280,
    maxChargekW: 210,
    efficiencyMilesPerKwh: 2.81,
  },
  {
    id: "chevy-bolt-euv",
    make: "Chevrolet",
    model: "Bolt EUV",
    years: "2022-2023",
    batteryKwh: 65,
    rangeMiles: 247,
    maxChargekW: 55,
    efficiencyMilesPerKwh: 3.8,
  },
  {
    id: "chevy-equinox-ev-fwd",
    make: "Chevrolet",
    model: "Equinox EV FWD",
    years: "2025-2026",
    batteryKwh: 85,
    rangeMiles: 319,
    maxChargekW: 150,
    efficiencyMilesPerKwh: 3.75,
  },
  {
    id: "chevy-equinox-ev-awd",
    make: "Chevrolet",
    model: "Equinox EV AWD",
    years: "2025-2026",
    batteryKwh: 85,
    rangeMiles: 285,
    maxChargekW: 150,
    efficiencyMilesPerKwh: 3.35,
  },
  {
    id: "chevy-blazer-ev-rwd",
    make: "Chevrolet",
    model: "Blazer EV RWD",
    years: "2024-2025",
    batteryKwh: 102,
    rangeMiles: 334,
    maxChargekW: 190,
    efficiencyMilesPerKwh: 3.27,
  },
  {
    id: "chevy-blazer-ev-awd",
    make: "Chevrolet",
    model: "Blazer EV AWD",
    years: "2024-2025",
    batteryKwh: 85,
    rangeMiles: 283,
    maxChargekW: 150,
    efficiencyMilesPerKwh: 3.33,
  },
  {
    id: "ford-f150-lightning",
    make: "Ford",
    model: "F-150 Lightning ER",
    years: "2022-2024",
    batteryKwh: 131,
    rangeMiles: 320,
    maxChargekW: 150,
    efficiencyMilesPerKwh: 2.44,
  },
  {
    id: "ford-mach-e-er-rwd",
    make: "Ford",
    model: "Mustang Mach-E ER RWD",
    years: "2023-2025",
    batteryKwh: 91,
    rangeMiles: 320,
    maxChargekW: 150,
    efficiencyMilesPerKwh: 3.52,
  },
  {
    id: "rivian-r1t",
    make: "Rivian",
    model: "R1T Large Pack (Gen 1)",
    years: "2022-2024",
    batteryKwh: 135,
    rangeMiles: 314,
    maxChargekW: 220,
    efficiencyMilesPerKwh: 2.33,
  },
  {
    id: "bmw-i4-edrive40",
    make: "BMW",
    model: "i4 eDrive40",
    years: "2022-2024",
    batteryKwh: 83.9,
    rangeMiles: 301,
    maxChargekW: 205,
    efficiencyMilesPerKwh: 3.59,
  },
  {
    id: "vw-id4-pro",
    make: "Volkswagen",
    model: "ID.4 Pro",
    years: "2022",
    batteryKwh: 82,
    rangeMiles: 275,
    maxChargekW: 135,
    efficiencyMilesPerKwh: 3.35,
  },
  {
    id: "vw-id4-pro-2023",
    make: "Volkswagen",
    model: "ID.4 Pro",
    years: "2023",
    batteryKwh: 82,
    rangeMiles: 275,
    maxChargekW: 170,
    efficiencyMilesPerKwh: 3.35,
  },
  {
    id: "vw-id4-pro-2024",
    make: "Volkswagen",
    model: "ID.4 Pro",
    years: "2024",
    batteryKwh: 82,
    rangeMiles: 291,
    maxChargekW: 175,
    efficiencyMilesPerKwh: 3.55,
  },
  {
    id: "lucid-air-gt",
    make: "Lucid",
    model: "Air GT",
    years: "2022-2024",
    batteryKwh: 112,
    rangeMiles: 516,
    maxChargekW: 300,
    efficiencyMilesPerKwh: 4.6,
  },
  {
    id: "mercedes-eqe-2023",
    make: "Mercedes-Benz",
    model: "EQE 350+",
    years: "2023",
    batteryKwh: 90.6,
    rangeMiles: 305,
    maxChargekW: 170,
    efficiencyMilesPerKwh: 3.37,
  },
  {
    id: "mercedes-eqe",
    make: "Mercedes-Benz",
    model: "EQE 350+",
    years: "2024",
    batteryKwh: 96.1,
    rangeMiles: 305,
    maxChargekW: 170,
    efficiencyMilesPerKwh: 3.17,
  },
  {
    id: "volvo-c40-recharge",
    make: "Volvo",
    model: "C40 Recharge Twin AWD",
    years: "2023",
    batteryKwh: 75,
    rangeMiles: 226,
    maxChargekW: 150,
    efficiencyMilesPerKwh: 3.01,
  },
  {
    id: "toyota-bz-awd",
    make: "Toyota",
    model: "bZ AWD",
    years: "2026",
    batteryKwh: 74.7,
    rangeMiles: 288,
    maxChargekW: 150,
    efficiencyMilesPerKwh: 3.86,
  },
  {
    id: "nissan-ariya-venture-fwd",
    make: "Nissan",
    model: "Ariya Venture+ FWD",
    years: "2023-2025",
    batteryKwh: 87,
    rangeMiles: 304,
    maxChargekW: 130,
    efficiencyMilesPerKwh: 3.49,
  },
];

// Typical non-member DCFC rates, 2026 US market survey
export const DEFAULT_NETWORK_PRICES: Record<string, number> = {
  "Tesla": 0.40,
  "Electrify America": 0.56,
  "ChargePoint": 0.48,
  "Blink": 0.59,
  "EVgo": 0.55,
  "Francis Energy": 0.39,
  "Ionna": 0.39,
  "Shell Recharge": 0.52,
  "Volta": 0.49,
  "Rivian": 0.44,
  "bp pulse": 0.55,
  "Buc-ee's": 0.40,
  "Default": 0.45,
};

export function getEVById(id: string): EVModel | undefined {
  return EV_DATABASE.find((ev) => ev.id === id);
}
